config/routes.rb
Rails.application.routes.draw do

  
  resources :interventions
  # resources :comments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/residential' =>'home#residential'
  get '/commercial' =>'home#commercial'
  get '/quote' =>'quote#quote'
  get '/index-RocketElevators.html' =>'home#index'
  get '/index-rocketElevators-residential.html' => 'home#residential'
  get '/index-rocketElevators-commercial.html' => 'home#commercial'
  get '/index-Quote.html' => 'quote#quote'
  post '/new_quote' =>'quote#new_quote'
  #post '/new_intervention' => 'intervention#new_intervention'
  post '/new_lead' =>'lead#new_lead'
  get '/chart' =>'charts#chart'
 
 #interventions

  get '/interventions' =>'interventions#interventions/new'
  get '/update_buildings' => 'interventions#update_buildings'
  get '/update_batteries' => 'interventions#update_batteries'
  get '/update_columns' => 'interventions#update_columns'
  get '/update_elevators' => 'interventions#update_elevators' 

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'home#index'

end

app/models/intervention.rb
class Intervention < ApplicationRecord

belongs_to :author
belongs_to :customer
belongs_to :building
belongs_to :battery
belongs_to :column
belongs_to :elevator
belongs_to :employee    

end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: [:show, :edit, :update, :destroy]

  # GET /interventions
  # GET /interventions.json
  def index
    @interventions = Intervention.all
  end

  # GET /interventions/1
  # GET /interventions/1.json
  def show
  end

  # GET /interventions/new
  def new_interventions
    intervention = Intervention.new
    intervention.customer_id = intervention_params["customer_id"]
    intervention.building_id = intervention_params["building_id"]
    intervention.battery_id = intervention_params["battery_id"]
    intervention.column_id = intervention_params["column_id"]
    intervention.elevator_id = intervention_params["elevator_id"]
    intervention.employee_id = intervention_params["employee_id"]
    

  end

  # GET /interventions/1/edit
  def edit
  end

  # POST /interventions
  # POST /interventions.json
  def create
    @intervention = Intervention.new(intervention_params)

    respond_to do |format|
      if @intervention.save
        format.html { redirect_to @intervention, notice: 'Intervention was successfully created.' }
        format.json { render :show, status: :created, location: @intervention }
      else
        format.html { render :new }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interventions/1
  # PATCH/PUT /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to @intervention, notice: 'Intervention was successfully updated.' }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1
  # DELETE /interventions/1.json
  def destroy
    @intervention.destroy
    respond_to do |format|
      format.html { redirect_to interventions_url, notice: 'Intervention was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

 
  def update_buildings
    @buildings = Building.where("customer_id = ?", params[:customers])
    puts  @buildings.size

    respond_to do |format|
      format.js
    end
    pp 'Allo building'
  end


  def update_batteries
    @batteries = Battery.where("building_id = ?", params[:buildings])
    puts  @batteries.size
    respond_to do |format|
      format.js
    end
    pp 'Allo building'
  end

  def update_columns
    @columns = Column.where("battery_id = ?", params[:batteries])
    puts  @columns.size
    respond_to do |format|
      format.js
    end
    pp 'Allo building'
  end

  def update_elevators
    @elevators = Elevator.where("column_id = ?", params[:columns])
    puts  @elevators.size
    respond_to do |format|
      format.js
    end
    pp 'Allo building'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intervention_params
      #params.fetch(:intervention, {})
      params.require(:customer).permit(:business_name, :user_id)
    end

end

 

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_with(model: intervention, local: true) do |form| %>
  <% if intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>
  
  

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interventions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>

        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<br>    <strong>Clients<strong>
<div class="control-group">

       <%= collection_select(:intervention, :customer_id, Customer.all, :id, :name, { :prompt => 'SELECT'}, { id: 'customer_select' } ) %>

</div>

<br>
<br>
    <strong>Buildings<strong>

<div class="control-group">
     
        <%= collection_select(:intervention, :building_id, Building.all, :id, :name, {:prompt => 'SELECT'}, { id: 'building_select' } ) %>
        
</div>

<br>
    <strong>Batteries<strong>

<div class="control-group">

       <%= collection_select(:intervention, :battery_id, Battery.all, :id, :building_id, {:prompt => 'SELECT'}, { id: 'battery_select' } ) %>
</div>

<br>
<br>
    <strong>Columns<strong>

<div class="control-group">

       <%= collection_select(:intervention, :column_id, Column.all, :id, :battery_id, {:prompt => 'NONE'}, { id: 'column_select' } ) %>
</div>

<br>
<br>
    <strong>Elevators<strong>

<%= collection_select(:intervention, :elevator_id, Elevator.all, :id, :column_id, {:prompt => 'NONE'}, { id:'elevator_select' } ) %>

<br>
<br>
<br>
<br>
    <strong>Employees<strong>

<%= collection_select(:employee, :employee_id, Employee.all, :id, :name, {:prompt => 'NONE'}, { :multiple => false } ) %>

<br>
<br>
<br>

<div class="col-md-8">
    <label for="contact:message">Project Description *</label>
    <textarea required maxlength="5000" rows="4" class="form-control" name="lead[project_description]" id="lead:message"></textarea>
</div>
<br>
<br>

 

<%#= <button id="submitbutton" class="btn btn-submit btn-lg" type="submit">SUBMIT &nbsp; <i class="fa fa-angle-right"></i></button> %>

<%= render 'form', intervention: @intervention %>           

<%= link_to 'Back', interventions_path %>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<%#= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/update_batteries.js.erb
console.log(" Hello");
$("#battery_select").empty()

$("#battery_select").append('<%= escape_javascript(render(:partial => @batteries)) %>');
console.log("let's Go!")

app/views/interventions/update_buildings.js.erb
console.log(" Hello");
$("#building_select").empty()

$("#building_select").append('<%= escape_javascript(render(:partial => @buildings)) %>');
console.log("let's Go!")

app/views/interventions/update_columns.js.erb
console.log(" Hello");
$("#column_select").empty()

$("#column_select").append('<%= escape_javascript(render(:partial => @columns)) %>');
console.log("let's Go!")

app/views/interventions/update_elevators.js.erb
console.log(" Hello");
$("#elevator_select").empty()

$("#elevator_select").append('<%= escape_javascript(render(:partial => @elevators)) %>');
console.log("let's Go!")